services:
  - type: worker
    name: chatgpt-ping
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    region: oregon
    envVars:
      - key: PYTHONUNBUFFERED
        value: "TRUE"