services:
  - type: web                      # আপনি worker না, web service চাই
    name: chatgpt-keepalive
    runtime: python
    region: oregon
    plan: free
    buildCommand: chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "TRUE"